include Makefile.conf

#### Perl  
SPARKVER= 0.46
SPARK 	= spark
SPARK_INST_PATH	= ${SICE_INST_PATH}
OSREV		= `uname -r`
#--------------------------------------------------------------------------#

all:    	install-spark

clean:		clean-spark

install-spark:	
	tar -zxvf sources/${SPARK}-${SPARKVER}.tar.gz
	cd ${SPARK}  ; cp spark ${SICE_INST_PATH}/bin
	touch install-SPARK

clean-spark:
	rm -rf ${SPARK} install-SPARK 
